version: '3.8'

services:
  # NESTJS API Gateway
  api-gateway:
    build: .    
    ports:
      - "3000:3000"
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DATABASE_URL=postgresql://user:pass@postgres:5432/analytics_db
      - DATABASE_HOST=postgres
      - REDIS_URL=redis://redis:6379
      - NODE_OPTIONS=--max-old-space-size=1024
    depends_on:
      - rabbitmq
      - postgres
      - redis

  # Pool of worker services
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # port for AMQP
      - "15672:15672" # Management panel (login/password: guest/guest)
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 5

  # DB
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: analytics_db
    ports:
      - "5432:5432"

  # Redis for Rate Limiting and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  ## prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  ## graphana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_SECURITY_ALLOW_EMBEDDING=true